// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCPc_R66vBWxJsAeK7oWVGzTGitpaVXZec',
    appId: '1:979917822315:web:77002af9c791aa7892942e',
    messagingSenderId: '979917822315',
    projectId: 'task-man-app-50758',
    authDomain: 'task-man-app-50758.firebaseapp.com',
    storageBucket: 'task-man-app-50758.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBp9H0X2D7RR38VnfOvAJ7h7FE0j0BPJI0',
    appId: '1:979917822315:android:3f8dbd5916e24e8692942e',
    messagingSenderId: '979917822315',
    projectId: 'task-man-app-50758',
    storageBucket: 'task-man-app-50758.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD7KLEF5QPm4VxXXTcTTPc9J6lZyPJ3m1M',
    appId: '1:979917822315:ios:cea413d1a7de527092942e',
    messagingSenderId: '979917822315',
    projectId: 'task-man-app-50758',
    storageBucket: 'task-man-app-50758.firebasestorage.app',
    iosBundleId: 'com.example.taskManangementApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD7KLEF5QPm4VxXXTcTTPc9J6lZyPJ3m1M',
    appId: '1:979917822315:ios:cea413d1a7de527092942e',
    messagingSenderId: '979917822315',
    projectId: 'task-man-app-50758',
    storageBucket: 'task-man-app-50758.firebasestorage.app',
    iosBundleId: 'com.example.taskManangementApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCPc_R66vBWxJsAeK7oWVGzTGitpaVXZec',
    appId: '1:979917822315:web:96e93ff23dbfc7a492942e',
    messagingSenderId: '979917822315',
    projectId: 'task-man-app-50758',
    authDomain: 'task-man-app-50758.firebaseapp.com',
    storageBucket: 'task-man-app-50758.firebasestorage.app',
  );

}