// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;



class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBG_IzF7i-zkKt7TsgYq4pbWGcWwWZ_SRE',
    appId: '1:124020674784:web:64ca36fa01fabe6e850085',
    messagingSenderId: '124020674784',
    projectId: 'task-management-453b8',
    authDomain: 'task-management-453b8.firebaseapp.com',
    storageBucket: 'task-management-453b8.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB9PRNYuOTn2k9as_7jjrbjCzk3wIt7zWc',
    appId: '1:124020674784:android:12c7bc896d9da91c850085',
    messagingSenderId: '124020674784',
    projectId: 'task-management-453b8',
    storageBucket: 'task-management-453b8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDECARcH8IevI64atCgbAmH-DjPlTrFkXw',
    appId: '1:124020674784:ios:883beb98de90696c850085',
    messagingSenderId: '124020674784',
    projectId: 'task-management-453b8',
    storageBucket: 'task-management-453b8.firebasestorage.app',
    iosBundleId: 'com.example.taskManangementApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDECARcH8IevI64atCgbAmH-DjPlTrFkXw',
    appId: '1:124020674784:ios:883beb98de90696c850085',
    messagingSenderId: '124020674784',
    projectId: 'task-management-453b8',
    storageBucket: 'task-management-453b8.firebasestorage.app',
    iosBundleId: 'com.example.taskManangementApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBG_IzF7i-zkKt7TsgYq4pbWGcWwWZ_SRE',
    appId: '1:124020674784:web:222037541bed901e850085',
    messagingSenderId: '124020674784',
    projectId: 'task-management-453b8',
    authDomain: 'task-management-453b8.firebaseapp.com',
    storageBucket: 'task-management-453b8.firebasestorage.app',
  );
}
